#!/bin/bash

# File:					Glog.sh
# Creation:				16-09-2010
# Last modification:	17-09-2010
# Description:
# 
# 

# #############################################
# Muestra el Help y termina.
#
# Nota: Utiliza la variable "logHelpExit" para
#       salir del script. En caso de no existir
#		termina la ejecucion con "0".

function Help {

	echo "$logCall - Global Log (v0.1)"
	echo
	echo "Usage: $logCall type message"
	echo
	echo "Message Type:"
	echo "-i	-I		Informative message"
	echo "-w	-W		Warning message"
	echo "-e	-E		Error message"
	echo "-se	-SE		Severe message"

	exit ${logHelpExit:-"0"}
}

# #########################################################
# Variables del script

logCall="Glog"
logFolder="/comandos/log"	# Esta comentado para poder hacer pruebas y no tener que crear la carpeta del TP...
#logPath="${GRUPO:-$PWD}${logFolder:+"$logFolder"}"
logFile="$logCall.log"
logName="$logPath/$logFile"

# ####################################################################
# Valido y obtengo los Argumentos del script

# Valida la cantidad de argumentos
if [ $# -ne 2 ]
then

	if [ $# -ne 1 -o "$1" != "--help" ]
	then
		logHelpExit="2"
	fi
	
	Help
fi

# Valida/Obtiene el tipo de mensaje a guardar
case "$1" in

	-i  | -I)	logType="Info";	 ;;
	-w  | -W)	logType="Warn";  ;;
	-e  | -E)	logType="Erro";  ;;
	-se | -SE)	logType="Serr";  ;;
	*)			logHelpExit="3"; Help; ;;

esac

# ####################################################################
# Verifico el tamaño del archivo del log

if [ -e $logName ]
then

	logMaxSize=${GLOG_MAX_SIZE:-"1048576"}
	logSize=$( ls -l "$logName" | cut -d' ' -f5  )
	logSizeWillBe=$( expr $logSize + ${#2} + 30  )

	if [ $logSizeWillBe -gt $logMaxSize  ]
	then

		echo "Log<$logFile> excedido de tamaño (${logMaxSize} b)."
		logSaveLast=${GLOG_LAST:-"15"}

		if [ $logSaveLast -gt 0 ]
		then

			echo "Log<$logFile> guardara los ultimos ${logSaveLast} registros." 
			tail -$logSaveLast $logName > "$logName.tmp"
			mv --force "$logName.tmp" "$logName"

		else
			echo -n "" > "$logName"
		fi
	fi

fi

# ####################################################################
# Creo el resto de la variables que uso para el registro del log

logMsg="$2"
logTime=$( date +"%Y/%m/%d %H:%M:%S" )

# ####################################################################
# Escribo en el log
echo "$logTime - $logType - $logMsg" >> "$logName"

exit 0

